tests:
  - type: http
    url: https://www.google.com
    verification_field: status_code
    success_value:
      - 200

  - type: telnet
    host: 127.0.0.1
    port: 22
    sucess_value: connected

  - type: command
    command: echo Returned output
    success_value: Returned output
